# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://stake.roomit.xyz
title: RoomIT
email: admin@roomit.xyz
author: Dwi
description: > # "Write an awesome description for your new site here. 
  The best validator staking node with support 24/7 and uptime!
copyright: 'Copyright &copy; 2022 Admin. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

