# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://stake.roomit.xyz
title: RoomIT
email: dwi@roomit.xyz
author: Dwi W G
description: > # "Write an awesome description for your new site here. 
  The best validator staking node with support 24/7 and uptime!
copyright: 'Copyright &copy; 2022 Admin. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: wechat
    url: https://t.me/roomit_nym
  - title: github
    url: https://github.com/luneareth/stake.roomit.xyz
  - title: drupal
    url: https://stake.roomit.xyz
